name: PR-VERIFY

on:
    pull_request:
        branches-ignore:
            - 'release/**'
permissions: write-all

jobs:
    code-lint:
        name: PR-VERIFY
        uses: netexknowledge/pruebaruben/.github/workflows/pr-verify-reusable.yml@master
        # env:
        #     VALIDATE_MARKDOWN: false # discutible
        #     NATURAL_LANGUAGE: false # discutible
        #     VALIDATE_OPENAPI: false
        #     GITHUB_TOKEN: ${{ github.token }}
        #     GH_TOKEN: ${{ github.token }}